# Generated by Django 6.0.3 on 2026-06-17 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('major', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year+'), ('alumni', 'Alumni')], max_length=10)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('interests', models.CharField(blank=True, max_length=300)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
