# Generated by Django 6.0.3 on 2026-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_backdrop_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('standard', 'Standard User'), ('host', 'Verified Host'), ('admin', 'Admin')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
