# Generated by Django 6.0.3 on 2026-07-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Meetup', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_registration_form',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='eligibility',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='prizes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_closes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='resources',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
