# Generated by Django 6.0.3 on 2026-03-07 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('sender', 'receiver')},
        ),
    ]
